// <auto-generated />
using System;
using BoatClub.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoatClub.Migrations
{
    [DbContext(typeof(BoatContext))]
    [Migration("20200623110146_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("BoatClub.Model.Boat", b =>
                {
                    b.Property<int>("BoatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HourlyRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoatId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Boat");
                });

            modelBuilder.Entity("BoatClub.Model.BoatTransaction", b =>
                {
                    b.Property<int>("BoatTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoatId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RentByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RentTo")
                        .HasColumnType("TEXT");

                    b.HasKey("BoatTransactionId");

                    b.HasIndex("RentByUserId");

                    b.ToTable("BoatTransaction");
                });

            modelBuilder.Entity("BoatClub.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BoatClub.Model.Boat", b =>
                {
                    b.HasOne("BoatClub.Model.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");
                });

            modelBuilder.Entity("BoatClub.Model.BoatTransaction", b =>
                {
                    b.HasOne("BoatClub.Model.User", "RentBy")
                        .WithMany()
                        .HasForeignKey("RentByUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
